### ISSUE TITLE
Improvement for Dice class

### ISSUE THREAD

**Issue by awo-dev** [hold11/CDIO_del1#4]
When we choose to optimize the Dice class, I'll suggest that we change it's constructor, and add a new one. The `faceCount` variable should have a default value (6), and a constructor without arguments. That constructor will by default use the value of `faceCount`. If faceCount is changed, that constructor will still use the value of the `faceCount` variable. 

Also, there should be a constructor with an `int` which then changes the `faceCount` for that specific dice.

Though, as most documentation are finished by now, this will only be an enhancement for the future (when this CDIO is uploaded, and we choose to optimize, so we can reuse).

**Comment by algorythm** [comment]
This issue has been moved to its own repository: [hold11/Dice](https://github.com/hold11/Dice/issues/1).
