### ISSUE TITLE
Changed the Player Class a bit

### ISSUE THREAD

**Issue by awo-dev** [hold11/CDIO_del1#8]
To make the tests run successfully, I had to add an additional method in the Player class. This obviously has to be added to the Class Diagram.

The method is a public static void called reset. It basically just resets the `playerCount` variable as well as the `players` list.

**Comment by trules** [comment]
Where can I find the class diagram? In the google drive folder there is the file `CDIO`/`del1`/ `UML_Diagrams`/ `CDIO 1/ Klasse diagrammer .mdzip.bak`, which does not seem to work. Who made the diagram?

**Comment by trules** [comment]
ProbIem solved.
